name: url_short
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asgiref=3.2.10
  - astroid=2.4.2
  - ca-certificates=2020.7.22
  - certifi=2020.6.20
  - django=3.1.2
  - isort=5.6.1
  - krb5=1.17.1
  - lazy-object-proxy=1.4.3
  - ld_impl_linux-64=2.35
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libpq=12.3
  - libstdcxx-ng=9.3.0
  - mccabe=0.6.1
  - ncurses=6.2
  - openssl=1.1.1h
  - pip=20.2.3
  - psycopg2=2.8.6
  - pylint=2.6.0
  - python=3.8.5
  - python_abi=3.8
  - pytz=2020.1
  - readline=8.0
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.33.0
  - sqlparse=0.3.1
  - tk=8.6.10
  - toml=0.10.1
  - wheel=0.35.1
  - wrapt=1.11.2
  - xz=5.2.5
  - zlib=1.2.11
